version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Bangkok
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_LOGLEVEL=verbose
      - REDIS_MAXMEMORY=${REDIS_MAXMEMORY}
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
